local state = require("pack.state")
local loader = require("pack.loader")
local pack = require("pack")

describe("pack import spec normalization (1.4)", function()
  it("preserves opts/config on a single spec (not just the bare url)", function()
    local out = pack._load_plugins({ "owner/repo.nvim", opts = { a = 1 }, lazy = true })
    assert.equals(1, #out)
    assert.equals("owner/repo.nvim", out[1][1])
    assert.same({ a = 1 }, out[1].opts)
    assert.is_true(out[1].lazy)
  end)

  it("preserves a single native-style (src=) spec", function()
    local out = pack._load_plugins({ src = "https://x/y", opts = { b = 2 } })
    assert.equals(1, #out)
    assert.equals("https://x/y", out[1].src)
    assert.same({ b = 2 }, out[1].opts)
  end)

  it("still treats a list of two bare strings as two plugins", function()
    local out = pack._load_plugins({ "u/a", "u/b" })
    assert.equals(2, #out)
  end)

  it("still treats a list of spec tables as a list", function()
    local out = pack._load_plugins({ { "u/a", opts = {} }, { "u/b" } })
    assert.equals(2, #out)
    assert.same({}, out[1].opts)
  end)
end)

describe("pack.state local plugin dir= (1.5)", function()
  it("uses dir= as the source instead of expanding to a GitHub URL", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    state.init({ plugins = { { "my-local-plugin", dir = dir } } })
    local p = state.get_plugins()["my-local-plugin"]
    assert.is_not_nil(p)
    assert.is_true(p.is_local, "dir= plugin must be marked local")
    assert.equals(dir, p.dir)
    assert.are_not.equal("https://github.com/my-local-plugin", p.url)
  end)

  it("is excluded from native install specs", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir, "p")
    state.init({ plugins = { { "my-local-plugin", dir = dir } } })
    local p = state.get_plugins()["my-local-plugin"]
    assert.is_nil(state.to_native_spec(p), "local plugins are not handed to native vim.pack")
  end)
end)

describe("pack.loader local plugin load (1.5)", function()
  it("adds the local dir to runtimepath and sources its plugin files", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. "/plugin", "p")
    vim.fn.writefile({ "_G.PACK_LOCAL_LOADED = true" }, dir .. "/plugin/init.lua")
    _G.PACK_LOCAL_LOADED = nil

    state.init({ plugins = { { "localdev", dir = dir } } })
    loader.load("localdev")

    assert.is_true(_G.PACK_LOCAL_LOADED, "local plugin file must be sourced")
    local on_rtp = vim.tbl_contains(
      vim.tbl_map(vim.fs.normalize, vim.api.nvim_list_runtime_paths()),
      vim.fs.normalize(dir)
    )
    assert.is_true(on_rtp, "local dir must be added to runtimepath")
    _G.PACK_LOCAL_LOADED = nil
  end)
end)

describe("pack.loader ftdetect cache (1.6)", function()
  local cache_file = vim.fn.stdpath("data") .. "/pack_ftdetect_cache.lua"

  after_each(function()
    if vim.fn.filereadable(cache_file) == 1 then
      vim.fn.delete(cache_file)
    end
  end)

  it("writes the ftdetect cache for a lazy installed plugin during flush", function()
    local dir = vim.fn.tempname()
    vim.fn.mkdir(dir .. "/ftdetect", "p")
    vim.fn.writefile({ "-- noop" }, dir .. "/ftdetect/mylang.lua")

    state.init({ plugins = { { "ftplug", lazy = true } } })
    -- Mimic native's load callback: records the plugin + its on-disk path.
    loader.load_fn({ spec = { name = "ftplug" }, path = dir })
    loader.flush_pending()

    assert.equals(1, vim.fn.filereadable(cache_file), "cache file must be generated by flush")
    local body = table.concat(vim.fn.readfile(cache_file), "\n")
    assert.is_true(body:find("mylang.lua", 1, true) ~= nil, "cache must reference the ftdetect file")
  end)
end)
